version: "3.8"

services:
  db_servicemgr:
    image: postgres:15
    container_name: db_servicemgr
    environment:
      POSTGRES_DB: servicemgr_db
      POSTGRES_USER: servicemgr_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - servicemgr_data:/var/lib/postgresql/data
    restart: always

  redis_server:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  service_manager:
    image: dheerajkumarp/fleet_service_manager:latest
    container_name: service_manager

    # ✅ Load env vars from the service.env file
    env_file:
      - ./service.env

    # ✅ Mount the firebase key JSON file inside the container
    volumes:
      - ./firebase_key.json:/app/secrets/firebase_key.json

    # ✅ Internal container-to-container DB + Redis connection
    environment:
      - DATABASE_URL=postgresql://servicemgr_user:password@db_servicemgr:5432/servicemgr_db
      - REDIS_URL=redis://redis_server:6379/0

    depends_on:
      - db_servicemgr
      - redis_server

    ports:
      - "8100:8100"
    restart: always

volumes:
  servicemgr_data:
  redis_data:
