services:
  db_servicemgr:
    image: postgres:15
    container_name: db_servicemgr
    environment:
      POSTGRES_DB: servicemgr_db
      POSTGRES_USER: servicemgr_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - servicemgr_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: fleet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  service_manager:
    build:
      context: ./service_manager
    image: fleet_service_manager:latest
    container_name: service_manager
    environment:
      - DATABASE_URL=postgresql://servicemgr_user:password@db_servicemgr:5432/servicemgr_db
      - REDIS_URL=redis://redis:6379/0
      - OAUTH2_ENV=dev
      - OAUTH2_URL="http://127.0.0.1:8100/api/auth/introspect"
      - REDIS_HOST=redis://redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=""
      - USE_REDIS=0
      - TOKEN_EXPIRY_HOURS=1
      - X_INTROSPECT_SECRET=Kjs#idjXw
    depends_on:
      - db_servicemgr
      - redis
    ports:
      - "8100:8100"
    volumes:
      - ./service_manager:/app
  

volumes:
  servicemgr_data:
  redis_data: